# Generated by Django 5.2.3 on 2025-07-20 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('telegram_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Telegram ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название категории')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Короткое описание категории')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('parent_category', models.ForeignKey(blank=True, help_text='Если подкатегория - выберите основную категорию', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='bot.category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название места')),
                ('description', models.TextField(verbose_name='Описание')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес')),
                ('average_check', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Средний чек')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Рейтинг')),
                ('web_link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на сайт')),
                ('map_link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на Яндекс Картах')),
                ('vk_link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка ВКонтакте')),
                ('instagram_link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка в Instagram')),
                ('telegram_link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка в Telegram')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('date_until', models.DateField(blank=True, null=True, verbose_name='Показывать до (включительно)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'ordering': ['-rating', 'name'],
            },
        ),
    ]
